---
# tasks file for deploy_apache_web

- name: Check Linux OS Family
  debug: var=ansible_os_family

- block: #RedHat

  - name: Install Apache Web Server for RedHat
    yum: name=httpd state=latest 

  - name: Start WebServer on RedHat and make it enable on boot
    service: name=httpd state=started enabled=yes 

  when: ansible_os_family == "RedHat"

- block: #Debian
  
  - name: Install Apache Web Server for Debian
    apt: name=apache2 state=latest

  - name: Start WebServer on Debian and make it enable on boot
    service: name=apache2 state=started enabled=yes 
  
  when: ansible_os_family == "Debian"

- name: Generate index.html file
  template: src=index.j2 dest={{ dest_folder }}/index.html mode=0555
  notify:
    - Restart Apache on Debian
    - Restart Apache on RedHat 
 
- name: Copy HomePage files to Web Server
  copy: src={{ item }} dest={{ dest_folder }} mode=0555
  with_fileglob: "*.jp*" 
    
  notify:
    - Restart Apache on Debian
    - Restart Apache on RedHat
