---
- name: My Super Playbook
  hosts: amazon
  become: yes

  vars:
    mytext: "Preved ot medveda"

  tasks:
  - name: Ping
    ping:

  - import_tasks: create_folders.yml
  - include_tasks: create_files.yml
    vars:
      mytext: "Overrided text"

      
