- name: Install Apache and Upload my Web Page
  hosts: linux
  become: yes

  vars:
    source_file: ./mywebsite/index.html
    dest: /var/www/html


  tasks:
  - name: Check Linux OS Family
    debug: var=ansible_os_family

  - block: #RedHat

    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest 

    - name: Copy MyHomePage to Servers
      copy: src={{ source_file }} dest={{ dest }} mode=0555
      notify: Restart Apache on RedHat

    - name: Start WebServer on RedHat and make it enable on boot
      service: name=httpd state=started enabled=yes 

    when: ansible_os_family == "RedHat"
  
  - block: #Debian
    
    - name: Install Apache Web Server for Debian
      apt: name=apache2 state=latest

    - name: Copy MyHomePage to Servers
      copy: src={{ source_file }} dest={{ dest }} mode=0555
      notify: Restart Apache on Debian

    - name: Start WebServer on Debian and make it enable on boot
      service: name=apache2 state=started enabled=yes 
    
    when: ansible_os_family == "Debian"
   
  handlers:
  - name: Restart Apache on Debian
    service: name=apache2 state=restarted
  
  - name: Restart Apache on RedHat
    service: name=httpd state=restarted

