---
amazon:
  hosts:
    aws-amazon:
      ansible_host: 3.250.31.63

redhat:
  hosts:
    aws-redhat:
      ansible_host: 54.216.120.3

rhel:
  children:
    amazon:
    redhat:

ubuntu:
  hosts:
    aws-ubuntu-1: 
      ansible_host: 34.241.148.45
    aws-ubuntu-2:
      ansible_host: 34.243.86.208

stage:
  hosts:
    aws-redhat: 
      ansible_host: 54.216.120.3
    aws-amazon: 
      ansible_host: 3.250.31.63
    aws-ubuntu-1: 
      ansible_host: 34.241.148.45

prod:
  hosts:
    aws-ubuntu-2:
      ansible_host: 34.243.86.208

linux:
  children:
    ubuntu:
    amazon:
    redhat:

windows:
  hosts:
    aws-windows-1:
      ansible_host: 34.240.198.153
    
    aws-windows-2: 
      ansible_host: 52.51.23.48

